{% set name = "summarytools" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/summarytools-{{ version }}.tar.gz
  sha256: 9b6f6e83e2590b81e0308568a68bc0fddc91e3467521c0033a20d62a0f66cdd7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.6
    - pandas >=1.4.0
    - ipython >=7.20.0
    - numpy >=1.18.5
    - matplotlib-base >=3.3.0

test:
  imports:
    - summarytools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/6chaoran/jupyter-summarytools
  summary: summarytools in jupyter notebook
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
